import { AssetRegistry, type AssetDefinition } from './AssetRegistry';

export const PROTOTYPE_CHARACTER_ANIMATION_CLIPS = ['Death', 'Duck', 'HitReact', 'Idle', 'Idle_Gun', 'Jump', 'Jump_Idle', 'Jump_Land', 'No', 'Punch', 'Run', 'Run_Gun', 'Run_Gun_Shoot', 'Walk', 'Walk_Gun', 'Wave', 'Weapon', 'Yes'] as const;

const definition = (value: AssetDefinition): AssetDefinition => value;

export const prototypeAssetDefinitions = [
  definition({ id: 'reactor-body', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/basemodule_E.gltf', runtimePath: '/assets/runtime/kaykit/basemodule_E.gltf', sourceBounds: { width: 2.22, height: 1.65, depth: 2.28 }, targetFootprint: { width: 3.7, depth: 3.7 }, transform: { scale: 1.65 }, visualCenter: { x: 0, y: 1.35, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2.2 }, workPoint: { x: 0, y: 0, z: 2.7 }, materialProfile: { roughness: 0.78, metalness: 0.15 }, shadowProfile: 'facility', visualHooks: ['reactor-core', 'state-beacon'] }),
  definition({ id: 'reactor-tower', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/structure_tall.gltf', runtimePath: '/assets/runtime/kaykit/structure_tall.gltf', sourceBounds: { width: 1.75, height: 2, depth: 1.75 }, transform: { scale: 1.45, offset: { x: 0, y: 1.2, z: 0 } }, visualCenter: { x: 0, y: 2.5, z: 0 }, materialProfile: { roughness: 0.72, metalness: 0.2 }, shadowProfile: 'facility' }),
  definition({ id: 'solar-panel', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/solarpanel.gltf', runtimePath: '/assets/runtime/kaykit/solarpanel.gltf', sourceBounds: { width: 0.9, height: 0.37, depth: 0.45 }, targetFootprint: { width: 1.4, depth: 0.8 }, transform: { scale: 1.5 }, visualCenter: { x: 0, y: 0.28, z: 0 }, entrancePoint: { x: 0, y: 0, z: 1.8 }, workPoint: { x: 0, y: 0, z: 1.2 }, materialProfile: { roughness: 0.58, metalness: 0.32 }, shadowProfile: 'facility' }),
  definition({ id: 'battery-body', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/basemodule_C.gltf', runtimePath: '/assets/runtime/kaykit/basemodule_C.gltf', sourceBounds: { width: 2, height: 1, depth: 2.21 }, targetFootprint: { width: 3.2, depth: 3.4 }, transform: { scale: 1.45 }, visualCenter: { x: 0, y: 0.75, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2 }, workPoint: { x: 0, y: 0, z: 2.5 }, materialProfile: { roughness: 0.75, metalness: 0.18 }, shadowProfile: 'facility', visualHooks: ['charge-flow'] }),
  definition({ id: 'battery-cargo', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/cargo_A_stacked.gltf', runtimePath: '/assets/runtime/kaykit/cargo_A_stacked.gltf', sourceBounds: { width: 1, height: 1, depth: 1 }, transform: { scale: 1.2, offset: { x: 0, y: 1, z: 0 } }, visualCenter: { x: 0, y: 1.5, z: 0 }, materialProfile: { roughness: 0.8, metalness: 0.12 }, shadowProfile: 'prop' }),
  definition({ id: 'mine-drill', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/drill_structure.gltf', runtimePath: '/assets/runtime/kaykit/drill_structure.gltf', sourceBounds: { width: 1.75, height: 2, depth: 1.75 }, targetFootprint: { width: 3.6, depth: 3.6 }, transform: { scale: 1.8 }, visualCenter: { x: 0, y: 1.8, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2.2 }, workPoint: { x: 0, y: 0, z: 2.5 }, materialProfile: { roughness: 0.82, metalness: 0.22 }, shadowProfile: 'facility', visualHooks: ['drill-motion', 'dust-particles'] }),
  definition({ id: 'habitat', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/basemodule_A.gltf', runtimePath: '/assets/runtime/kaykit/basemodule_A.gltf', sourceBounds: { width: 2.25, height: 1, depth: 2.35 }, targetFootprint: { width: 3.8, depth: 3.8 }, transform: { scale: 1.65 }, visualCenter: { x: 0, y: 0.82, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2.3 }, workPoint: { x: 0, y: 0, z: 2.8 }, materialProfile: { roughness: 0.8, metalness: 0.12 }, shadowProfile: 'facility', visualHooks: ['window-light'] }),
  definition({ id: 'habitat-annex', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/basemodule_D.gltf', runtimePath: '/assets/runtime/kaykit/basemodule_D.gltf', sourceBounds: { width: 2.44, height: 1, depth: 2.14 }, transform: { scale: 1.15 }, visualCenter: { x: 0, y: 0.58, z: 0 }, materialProfile: { roughness: 0.8, metalness: 0.12 }, shadowProfile: 'facility', visualHooks: ['window-light'] }),
  definition({ id: 'habitat-tunnel', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/tunnel_straight_A.gltf', runtimePath: '/assets/runtime/kaykit/tunnel_straight_A.gltf', sourceBounds: { width: 2, height: 0.6, depth: 0.93 }, transform: { scale: 1.05 }, visualCenter: { x: 0, y: 0.5, z: 0 }, materialProfile: { roughness: 0.8, metalness: 0.12 }, shadowProfile: 'facility' }),
  definition({ id: 'oxygen', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/basemodule_B.gltf', runtimePath: '/assets/runtime/kaykit/basemodule_B.gltf', sourceBounds: { width: 2.1, height: 1, depth: 2.25 }, targetFootprint: { width: 3.6, depth: 3.6 }, transform: { scale: 1.55 }, visualCenter: { x: 0, y: 0.78, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2.2 }, workPoint: { x: 0, y: 0, z: 2.7 }, materialProfile: { roughness: 0.8, metalness: 0.12 }, shadowProfile: 'facility', visualHooks: ['oxygen-pulse'] }),
  definition({ id: 'oxygen-vent', sourcePack: 'quaternius-modular', originalPath: 'assets-source/quaternius-modular/Models/Props/Prop_Vent_Big.gltf', runtimePath: '/assets/runtime/modular/Prop_Vent_Big.gltf', sourceBounds: { width: 2, height: 1.1, depth: 0.99 }, transform: { scale: 0.65, rotationY: Math.PI / 2, offset: { x: 0, y: 1.05, z: 0 } }, visualCenter: { x: 0, y: 1.4, z: 0 }, materialProfile: { roughness: 0.7, metalness: 0.28 }, shadowProfile: 'prop' }),
  definition({ id: 'road-tile', sourcePack: 'quaternius-modular', originalPath: 'assets-source/quaternius-modular/Models/Platforms/Platform_DarkPlates.gltf', runtimePath: '/assets/runtime/modular/Platform_DarkPlates.gltf', sourceBounds: { width: 4, height: 0.18, depth: 4 }, targetFootprint: { width: 4, depth: 4 }, transform: { scale: 1 }, visualCenter: { x: 0, y: 0.09, z: 0 }, materialProfile: { roughness: 0.88, metalness: 0.12 }, shadowProfile: 'ground' }),
  definition({ id: 'street-light', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/lights.gltf', runtimePath: '/assets/runtime/kaykit/lights.gltf', sourceBounds: { width: 0.68, height: 1, depth: 0.68 }, transform: { scale: 1.4 }, visualCenter: { x: 0, y: 0.7, z: 0 }, materialProfile: { roughness: 0.7, metalness: 0.16, emissiveIntensity: 1 }, shadowProfile: 'prop', visualHooks: ['warm-night-light'] }),
  definition({ id: 'floor-light', sourcePack: 'quaternius-modular', originalPath: 'assets-source/quaternius-modular/Models/Props/Prop_Light_Floor.gltf', runtimePath: '/assets/runtime/modular/Prop_Light_Floor.gltf', sourceBounds: { width: 0.3, height: 0.12, depth: 0.3 }, transform: { scale: 0.4 }, visualCenter: { x: 0, y: 0.06, z: 0 }, materialProfile: { roughness: 0.7, metalness: 0.2, emissiveIntensity: 0.7 }, shadowProfile: 'ground' }),
  definition({ id: 'expansion-pad', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/landingpad_large.gltf', runtimePath: '/assets/runtime/kaykit/landingpad_large.gltf', sourceBounds: { width: 2.5, height: 0.5, depth: 2.5 }, targetFootprint: { width: 5, depth: 5 }, transform: { scale: 2 }, visualCenter: { x: 0, y: 0.5, z: 0 }, entrancePoint: { x: 0, y: 0, z: 2.8 }, materialProfile: { roughness: 0.86, metalness: 0.1 }, shadowProfile: 'ground' }),
  definition({ id: 'rock-small-a', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/rock_A.gltf', runtimePath: '/assets/runtime/kaykit/rock_A.gltf', sourceBounds: { width: 1, height: 0.8, depth: 1 }, transform: { scale: 1.5 }, visualCenter: { x: 0, y: 0.4, z: 0 }, materialProfile: { roughness: 1, metalness: 0 }, shadowProfile: 'prop' }),
  definition({ id: 'rock-small-b', sourcePack: 'kaykit-space', originalPath: 'assets-source/kaykit-space/Models/rock_B.gltf', runtimePath: '/assets/runtime/kaykit/rock_B.gltf', sourceBounds: { width: 1, height: 0.8, depth: 1 }, transform: { scale: 1.4 }, visualCenter: { x: 0, y: 0.4, z: 0 }, materialProfile: { roughness: 1, metalness: 0 }, shadowProfile: 'prop' }),
  definition({ id: 'rock-large', sourcePack: 'quaternius-ultimate', originalPath: 'assets-source/quaternius-ultimate/Environment/Models/Rock_Large_1.gltf', runtimePath: '/assets/runtime/ultimate/Rock_Large_1.gltf', sourceBounds: { width: 7.67, height: 3.29, depth: 7.34 }, transform: { scale: 0.58 }, visualCenter: { x: 0, y: 0.8, z: 0 }, materialProfile: { roughness: 1, metalness: 0, tint: '#c6d5da' }, shadowProfile: 'prop' }),
  definition({ id: 'supply-crate', sourcePack: 'quaternius-essentials', originalPath: 'assets-source/quaternius-essentials/Models/Prop_Crate.gltf', runtimePath: '/assets/runtime/essentials/Prop_Crate.gltf', sourceBounds: { width: 1.57, height: 1.5, depth: 1.5 }, transform: { scale: 0.55 }, visualCenter: { x: 0, y: 0.4, z: 0 }, materialProfile: { roughness: 0.84, metalness: 0.12 }, shadowProfile: 'prop' }),
  definition({ id: 'prototype-astronaut', animationClips: PROTOTYPE_CHARACTER_ANIMATION_CLIPS, sourcePack: 'quaternius-ultimate', originalPath: 'assets-source/quaternius-ultimate/Characters/Models/Astronaut_FinnTheFrog.gltf', runtimePath: '/assets/runtime/ultimate/Astronaut_FinnTheFrog.gltf', sourceBounds: { width: 1, height: 2, depth: 1 }, transform: { scale: 0.43 }, visualCenter: { x: 0, y: 0.5, z: 0 }, materialProfile: { roughness: 0.75, metalness: 0.1 }, shadowProfile: 'character' }),
  definition({ id: 'prototype-astronaut-rae', animationClips: PROTOTYPE_CHARACTER_ANIMATION_CLIPS, sourcePack: 'quaternius-ultimate', originalPath: 'assets-source/quaternius-ultimate/Characters/Models/Astronaut_RaeTheRedPanda.gltf', runtimePath: '/assets/runtime/ultimate/Astronaut_RaeTheRedPanda.gltf', sourceBounds: { width: 1, height: 2, depth: 1 }, transform: { scale: 0.43 }, visualCenter: { x: 0, y: 0.5, z: 0 }, materialProfile: { roughness: 0.75, metalness: 0.1 }, shadowProfile: 'character' }),
  definition({ id: 'prototype-astronaut-barbara', animationClips: PROTOTYPE_CHARACTER_ANIMATION_CLIPS, sourcePack: 'quaternius-ultimate', originalPath: 'assets-source/quaternius-ultimate/Characters/Models/Astronaut_BarbaraTheBee.gltf', runtimePath: '/assets/runtime/ultimate/Astronaut_BarbaraTheBee.gltf', sourceBounds: { width: 1, height: 2, depth: 1 }, transform: { scale: 0.43 }, visualCenter: { x: 0, y: 0.5, z: 0 }, materialProfile: { roughness: 0.75, metalness: 0.1 }, shadowProfile: 'character' }),
] as const;

export const prototypeAssetRegistry = new AssetRegistry();
prototypeAssetDefinitions.forEach((asset) => prototypeAssetRegistry.register(asset));

export function requirePrototypeAsset(id: string): AssetDefinition {
  const asset = prototypeAssetRegistry.get(id);
  if (!asset) throw new Error(`Prototype asset "${id}" is not registered.`);
  return asset;
}
