export const tr = {
  app: { title: 'Gözlemci İşletim Sistemi' },
  navigation: { primaryLabel: 'Ana çalışma alanları', colony: 'KOLONİ', protocols: 'PROTOKOLLER', debugger: 'HATA AYIKLAMA' },
  workspace: {
    colony: { title: 'KOLONİ / NIVALIS', foundationStatus: 'Dünya görünümü teknik iskeleti hazır.', prototypeStatus: 'Koloni dünya sunumu · iş gücü ve bakım yetkili simülasyon durumuna bağlı' },
    protocols: { title: 'PROTOKOLLER', foundationStatus: 'Protokol düzenleyici entegrasyon sınırı hazır.' },
    debugger: { title: 'HATA AYIKLAMA', foundationStatus: 'Hata Ayıklama çalışma alanı teknik iskeleti hazır.' },
  },
  prototype: {
    worldStatus: 'SİMÜLASYONA BAĞLI DÜNYA',
    debug: { badge: 'DEV · FAZ 4', title: 'PROTOTİP KONTROLLERİ', hide: 'Paneli gizle', show: 'Kontrolleri göster', time: 'Günün zamanı', snow: 'Kar', fog: 'Sis', reactor: 'Reaktör durumu', mine: 'Maden durumu', colonists: 'Kolonici sayısı', camera: 'Kamera odağı', quality: 'Kalite profili', safeAreas: 'Güvenli alan maskeleri' },
    states: { normal: 'Normal', boost: 'Boost', interlocked: 'Güvenlik kilidinde', maintenance: 'Bakımda', working: 'Çalışıyor', offline: 'Çevrimdışı' },
    camera: { overview: 'Genel görünüm', reset: 'Koloniyi göster', reactor: 'Reaktör', mine: 'Maden', habitat: 'Habitat' },
    quality: { low: 'Düşük', medium: 'Orta', high: 'Yüksek' },
    safe: { right: 'SAĞ PANEL GÜVENLİ ALANI', bottom: 'ALT NAVİGASYON GÜVENLİ ALANI' },
    legend: { pan: 'Sürükle: kamerayı kaydır', zoom: 'Tekerlek: yakınlaştır' },
    inspector: { asset: 'Çalışma asset kimliği', chain: 'Üst nesne zinciri', object: 'Nesne / mesh', parent: 'Üst nesne', position: 'Dünya konumu', prompt: 'İncelemek için dünyadaki bir nesneye tıklayın.', source: 'Kaynak paket', title: 'DEV NESNE İNCELEYİCİ', toggle: 'Nesne inceleyiciyi etkinleştir' },
    metrics: { draw: 'Çizim', geometry: 'Geometri', lights: 'Işık', particles: 'Parçacık', textures: 'Doku', triangles: 'Üçgen' },
  },
  layoutReview: {
    adjacency: 'YAKINLIK', candidate: 'ADAY {{letter}}', composition: 'KOMPOZİSYON', connected: 'Bağlı', default: 'Default', defaultSelected: 'Faz 3 sabit yerleşim · dondurulmuş', expansion: 'GENİŞLEME', navigation: 'NAVİGASYON', newSeed: 'Yeni Tohum Üret', next: 'Sonraki Aday', notFrozen: 'DEV önizleme · nihai seçim değil', overlay: 'Yerleşim doğrulama katmanı', previous: 'Önceki Aday', productionPending: 'Nihai yerleşim kullanıcı seçimi sonrasında dondurulacaktır.', generationFallback: 'Üretilen yerleşim alınamadı; Faz 3 sabit yerleşimi (Default) gösteriliyor.', profile: 'PROFİL', readability: 'EKRAN OKUNABİLİRLİĞİ', road: 'YOL KALİTESİ', roadNetwork: 'YOL AĞI', seed: 'TOHUM', styles: { Compact: 'Kompakt', Distributed: 'Dağıtık', Linear: 'Doğrusal' }, terrain: 'ARAZİ KULLANIMI', title: 'YERLEŞİM ADAYLARI', total: 'TOPLAM PUAN', valid: 'GEÇERLİ', yes: 'Evet',
    structure: 'YERLEŞİM YAPISI', habitatStructure: 'HABİTAT YAPISI', roadTopology: 'YOL TOPOLOJİSİ', roadTopologyValue: '{{orientation}} · {{turns}} dönüş', junction: 'KAVŞAK', gameplayFacilities: 'OYUN TESİSİ', visualModules: 'GÖRSEL MODÜL', expansionPosition: 'GENİŞLEME KONUMU', terrainSilhouette: 'ARAZİ SİLUETİ', structuralDifference: 'YAPISAL FARK', signature: 'ÇEŞİTLİLİK İMZASI',
    archetypes: { 'central-spine': 'Merkezi omurga', 'l-shaped': 'L biçimli koloni', 't-junction': 'T kavşaklı koloni', 'offset-hub': 'Ofset merkez', 'split-core': 'İki çekirdekli koloni' },
    habitatVariants: { 'compact-pod': 'Kompakt yaşam podu', courtyard: 'Avlulu yerleşke', 'linear-compound': 'Doğrusal yerleşke', 'clustered-habitat': 'Kümeli habitat', 'service-yard': 'Servis avlulu habitat' },
    terrainVariants: { elongated: 'Uzun plato', 'wide-central-shelf': 'Geniş merkez rafı', 'offset-industrial-shelf': 'Ofset endüstri rafı', 'split-ledge': 'Bölünmüş çıkıntı' },
    expansionRelations: { 'east-road-end': 'Doğu yol ucu', 'west-road-end': 'Batı yol ucu', 'north-side-branch': 'Kuzey yan kolu', 'south-outer-shelf': 'Güney dış rafı' },
    orientations: { horizontal: 'Yatay omurga', vertical: 'Dikey omurga', diagonal: 'Çapraz omurga', mixed: 'Kırıklı omurga' },
    seedSweep: { averageCandidates: 'ORTALAMA ADAY', averageMs: 'ORTALAMA ÜRETİM SÜRESİ', averageSignatures: 'ORTALAMA YAPISAL İMZA', minimumSignatures: 'EN AZ YAPISAL İMZA', failed: 'BAŞARISIZ', highest: 'EN YÜKSEK PUAN', lowest: 'EN DÜŞÜK PUAN', tested: 'TEST EDİLEN TOHUM', title: 'TOHUM TARAMASI', valid: 'GEÇERLİ' },
  },
  simulationDiagnostic: {
    actions: {
      advance60: '+60 Sim. Dakika İlerle',
      maintenancePriority: 'Bakım Önceliği: {{priority}}',
      mine: { boost: 'Maden: Boost', eco: 'Maden: Eco', normal: 'Maden: Normal', offline: 'Madeni Devre Dışı Bırak', online: 'Madeni Etkinleştir' },
      mineCondition: 'Maden Kondisyonu: {{condition}}',
      pause: 'Duraklat',
    },
    command: { none: 'SON KOMUT: Yok', result: 'SON KOMUT: {{status}}{{reason}}' },
    conditionFixtures: 'Maden kondisyon denemeleri',
    empty: { maintenance: 'BAKIM: Bakım ihtiyacı yok', travel: 'YOLCULUK: Kimse yolda değil' },
    facility: {
      condition: 'KONDİSYON {{condition}} · {{band}} · AŞINMA {{wear}}/sa.',
      workforce: 'İŞ GÜCÜ {{assigned}}/{{nominal}} · TESİSTE {{onSite}}',
    },
    help: {
      active: 'Şu anda çalışabilecek kolonici sayısı',
      assigned: 'Bir tesis veya bakım görevine ayrılmış kolonici',
      available: 'Aktif fakat şu anda görevi olmayan kolonici',
      condition: 'Kondisyon tesisin 0–100 teknik sağlığıdır; aşınma çalıştıkça bu değeri düşüren orandır.',
      resting: 'Habitat içinde dinlenen kolonici',
      traveling: 'Bir göreve veya Habitat’a fiziksel olarak hareket eden kolonici',
    },
    labels: {
      active: 'AKTİF İŞ GÜCÜ', assigned: 'GÖREVE ATANMIŞ', available: 'MÜSAİT', day: 'GÜN', dayPhase: 'ZAMAN DİLİMİ', elapsed: 'GEÇEN SİM. DAKİKASI',
      energyPriority: 'ENERJİ ÖNCELİĞİ', localTime: 'YEREL SAAT (SİM.)', mineState: 'MADEN DURUMU', mode: 'MOD', population: 'NÜFUS',
      resting: 'DİNLENİYOR', simStep: 'SİMÜLASYON ADIMI', speed: 'HIZ', traveling: 'YOLDA', worldPresentation: 'DÜNYA GÖRSEL DURUMU', x1Rate: '×1 ORANI',
    },
    maintenance: {
      detail: 'MALZEME {{material}}{{consumed}} · KALAN {{remaining}} sim. dk.{{reason}}',
      workforce: 'ÖNCELİK {{priority}} · İŞÇİ {{assigned}}/{{required}}',
    },
    maintenancePriority: 'Maden bakım önceliği',
    mineCommands: 'Maden simülasyon komutları',
    minutes: '{{count}} dk.',
    phaseBadge: 'DEV · FAZ 3',
    resourceRate: '+{{production}} −{{consumption}} = {{net}}/sa.',
    speedControls: 'Simülasyon hız kontrolleri',
    title: 'SİMÜLASYON DURUMU',
    travel: {
      detail: '{{purpose}} · İLERLEME %{{progress}} · KALAN {{remaining}} sim. dk.',
      route: '{{from}} → {{to}}',
    },
    values: {
      commandStatus: { applied: 'Uygulandı', blocked: 'Engellendi', delayed: 'Geciktirildi', failed: 'Başarısız' },
      condition: { critical: 'Kritik', failed: 'Arızalı', healthy: 'Sağlıklı', worn: 'Yıpranmış' },
      consumed: ' · TÜKETİLDİ',
      dayPhase: { day: 'Gündüz', night: 'Gece' },
      facilityState: { failed: 'Arızalı', interlocked: 'Güvenlik kilidinde', maintenance: 'Bakımda', offline: 'Devre dışı', online: 'Aktif', standby: 'Beklemede', starting: 'Başlatılıyor' },
      location: { 'battery-01': 'Batarya', habitat: 'Habitat', 'mine-01': 'Maden', 'oxygen-processor-01': 'Oksijen İşleyici', 'reactor-01': 'Reaktör' },
      maintenanceStatus: { completed: 'Bakım tamamlandı', 'in-progress': 'Bakım yapılıyor', requested: 'Bakım istendi', traveling: 'Bakım ekibi yolda', 'waiting-resources': 'Kaynak bekliyor', 'waiting-workforce': 'İş gücü bekliyor' },
      mode: { boost: 'Boost (Yüksek Güç)', eco: 'Eco (Tasarruf)', normal: 'Normal' },
      none: 'Yok',
      paused: 'DURAKLATILDI',
      priority: { critical: 'Kritik', high: 'Yüksek', low: 'Düşük', normal: 'Normal' },
      resource: { energy: 'ENERJİ', material: 'MALZEME', oxygen: 'OKSİJEN' },
      running: 'ÇALIŞIYOR',
      travelPurpose: { 'return-to-habitat': 'Habitat’a dönüyor', 'to-assignment': 'Göreve gidiyor' },
    },
    x1Rate: '1 sim. dk. ≈ {{value}} gerçek sn.',
  },
} as const;
