export const tr = {
  app: { title: 'Gözlemci İşletim Sistemi' },
  navigation: { primaryLabel: 'Ana çalışma alanları', colony: 'KOLONİ', protocols: 'PROTOKOLLER', debugger: 'HATA AYIKLAMA' },
  workspace: {
    colony: { title: 'KOLONİ / NIVALIS', foundationStatus: 'Dünya görünümü teknik iskeleti hazır.', prototypeStatus: 'Koloni dünya sunumu · iş gücü ve bakım yetkili simülasyon durumuna bağlı' },
    protocols: { title: 'PROTOKOLLER', foundationStatus: 'Protokol düzenleyici entegrasyon sınırı hazır.' },
    debugger: { title: 'HATA AYIKLAMA', foundationStatus: 'Hata Ayıklama çalışma alanı teknik iskeleti hazır.' },
  },
  prototype: {
    worldStatus: 'SİMÜLASYONA BAĞLI DÜNYA',
    debug: { badge: 'DEV · FAZ 4', title: 'PROTOTİP KONTROLLERİ', hide: 'Paneli gizle', show: 'Kontrolleri göster', time: 'Günün zamanı', snow: 'Kar', fog: 'Sis', reactor: 'Reaktör durumu', mine: 'Maden durumu', colonists: 'Kolonici sayısı', camera: 'Kamera odağı', quality: 'Kalite profili', safeAreas: 'Güvenli alan maskeleri' },
    states: { normal: 'Normal', boost: 'Boost', interlocked: 'Güvenlik kilidinde', maintenance: 'Bakımda', working: 'Çalışıyor', offline: 'Çevrimdışı' },
    camera: { overview: 'Genel görünüm', reset: 'Koloniyi göster', reactor: 'Reaktör', mine: 'Maden', habitat: 'Habitat' },
    quality: { low: 'Düşük', medium: 'Orta', high: 'Yüksek' },
    safe: { right: 'SAĞ PANEL GÜVENLİ ALANI', bottom: 'ALT NAVİGASYON GÜVENLİ ALANI' },
    legend: { pan: 'Sürükle: kamerayı kaydır', zoom: 'Tekerlek: yakınlaştır' },
    inspector: { asset: 'Çalışma asset kimliği', chain: 'Üst nesne zinciri', object: 'Nesne / mesh', parent: 'Üst nesne', position: 'Dünya konumu', prompt: 'İncelemek için dünyadaki bir nesneye tıklayın.', source: 'Kaynak paket', title: 'DEV NESNE İNCELEYİCİ', toggle: 'Nesne inceleyiciyi etkinleştir' },
    metrics: { draw: 'Çizim', geometry: 'Geometri', lights: 'Işık', particles: 'Parçacık', textures: 'Doku', triangles: 'Üçgen' },
  },
  layoutReview: {
    adjacency: 'YAKINLIK', candidate: 'ADAY {{letter}}', composition: 'KOMPOZİSYON', connected: 'Bağlı', default: 'Default', defaultSelected: 'Faz 3 sabit yerleşim · dondurulmuş', expansion: 'GENİŞLEME', navigation: 'NAVİGASYON', newSeed: 'Yeni Tohum Üret', next: 'Sonraki Aday', notFrozen: 'DEV önizleme · nihai seçim değil', overlay: 'Yerleşim doğrulama katmanı', previous: 'Önceki Aday', productionPending: 'Nihai yerleşim kullanıcı seçimi sonrasında dondurulacaktır.', generationFallback: 'Üretilen yerleşim alınamadı; Faz 3 sabit yerleşimi (Default) gösteriliyor.', profile: 'PROFİL', readability: 'EKRAN OKUNABİLİRLİĞİ', road: 'YOL KALİTESİ', roadNetwork: 'YOL AĞI', seed: 'TOHUM', styles: { Compact: 'Kompakt', Distributed: 'Dağıtık', Linear: 'Doğrusal' }, terrain: 'ARAZİ KULLANIMI', title: 'YERLEŞİM ADAYLARI', total: 'TOPLAM PUAN', valid: 'GEÇERLİ', yes: 'Evet',
    structure: 'YERLEŞİM YAPISI', habitatStructure: 'HABİTAT YAPISI', roadTopology: 'YOL TOPOLOJİSİ', roadTopologyValue: '{{orientation}} · {{turns}} dönüş', junction: 'KAVŞAK', gameplayFacilities: 'OYUN TESİSİ', visualModules: 'GÖRSEL MODÜL', expansionPosition: 'GENİŞLEME KONUMU', terrainSilhouette: 'ARAZİ SİLUETİ', structuralDifference: 'YAPISAL FARK', signature: 'ÇEŞİTLİLİK İMZASI',
    archetypes: { 'central-spine': 'Merkezi omurga', 'l-shaped': 'L biçimli koloni', 't-junction': 'T kavşaklı koloni', 'offset-hub': 'Ofset merkez', 'split-core': 'İki çekirdekli koloni' },
    habitatVariants: { 'compact-pod': 'Kompakt yaşam podu', courtyard: 'Avlulu yerleşke', 'linear-compound': 'Doğrusal yerleşke', 'clustered-habitat': 'Kümeli habitat', 'service-yard': 'Servis avlulu habitat' },
    terrainVariants: { elongated: 'Uzun plato', 'wide-central-shelf': 'Geniş merkez rafı', 'offset-industrial-shelf': 'Ofset endüstri rafı', 'split-ledge': 'Bölünmüş çıkıntı' },
    expansionRelations: { 'east-road-end': 'Doğu yol ucu', 'west-road-end': 'Batı yol ucu', 'north-side-branch': 'Kuzey yan kolu', 'south-outer-shelf': 'Güney dış rafı' },
    orientations: { horizontal: 'Yatay omurga', vertical: 'Dikey omurga', diagonal: 'Çapraz omurga', mixed: 'Kırıklı omurga' },
    seedSweep: { averageCandidates: 'ORTALAMA ADAY', averageMs: 'ORTALAMA ÜRETİM SÜRESİ', averageSignatures: 'ORTALAMA YAPISAL İMZA', minimumSignatures: 'EN AZ YAPISAL İMZA', failed: 'BAŞARISIZ', highest: 'EN YÜKSEK PUAN', lowest: 'EN DÜŞÜK PUAN', tested: 'TEST EDİLEN TOHUM', title: 'TOHUM TARAMASI', valid: 'GEÇERLİ' },
  },
  protocol: {
    commandReason: {
      CAPABILITY_NOT_AVAILABLE: 'Eylemin karşılığı olan ayar hedef tesiste bulunmuyor.',
      COMMAND_CONFLICT_EQUAL_PRIORITY: 'Aynı öncelikteki iki protokol aynı ayara farklı değer istedi; hiçbiri uygulanmadı.',
      COMMAND_SUPERSEDED_BY_PRIORITY: 'Aynı ayara daha yüksek öncelikli bir protokol komut verdi; bu komut uygulanmadı.',
      COMMAND_VALUE_INVALID: 'Komutun taşıdığı değer geçersiz.',
      COMMAND_VALUE_UNSUPPORTED: 'Tesis bu değeri desteklemiyor.',
      SAFETY_CONDITION_LIMIT: 'Tesisin kondisyonu boost için gereken alt sınırın altında; güvenlik kilidi komutu durdurdu.',
      SAFETY_INTERLOCK_ACTIVE: 'Tesis güvenlik kilidinde; kilit açılmadan bu komut uygulanamaz.',
      SAFETY_RAMP_REQUIRED: 'Bu tesiste mod değişimi kademeli yapılmalı; doğrudan mod komutu uygulanmadı.',
      SAFETY_WORKFORCE_MINIMUM: 'Tesiste boost için gereken sayıda kolonici yok; güvenlik kilidi komutu durdurdu.',
      TARGET_FAILED: 'Hedef tesis arızalı; bakım yapılmadan komut uygulanamaz.',
      TARGET_MAINTENANCE: 'Hedef tesis bakımda; bakım bitene kadar komut uygulanamaz.',
      TARGET_NOT_FOUND: 'Komutun hedeflediği tesis bulunamadı.',
    },
    error: {
      'trigger-missing': 'Protokolde başlangıç tetikleyicisi yok; otomasyon kendiliğinden başlayamaz.',
      'multiple-root-triggers': 'Bir protokolde yalnız bir başlangıç tetikleyicisi olabilir; fazlasını ayrı bir protokole taşıyın.',
      'action-required-field-missing': 'Eylemde eksik alan var: hedef tesis veya ayarlanacak değer belirtilmemiş.',
      'action-value-type': 'Eylem için seçilen değer bu ayarın kabul ettiği türde değil.',
      'compare-operand-type': 'Karşılaştırılan iki değer aynı türde değil; bu karşılaştırma yapılamaz.',
      'compare-operand-missing': 'Karşılaştırma düğümünün bir girişi boş; karşılaştırılacak değer bağlanmalı.',
      'and-input-missing': 'VE düğümünün iki koşul girişi de bağlı olmalı.',
      'graph-cycle': 'Bağlantılar kendi üzerine dönüyor; döngü içeren protokol uygulanamaz.',
      'delay-duration-out-of-range': 'Geciktirme süresi izin verilen aralığın dışında.',
      'edge-port-incompatible': 'Bu bağlantı birbirine uymayan iki ucu birleştiriyor.',
      'capability-unavailable': 'Seçilen ölçüm veya eylem bu koloninin mevcut tesislerinde bulunmuyor.',
      'deleted-facility-reference': 'Protokol artık var olmayan bir tesise bağlı.',
    },
    warning: {
      'action-value-unchanged': 'Bu eylem tesisi zaten bulunduğu değere ayarlıyor olabilir.',
      'no-affected-facility': 'Protokol şu anda hiçbir tesisi etkilemiyor; uygun bir tesis kurulduğunda çalışabilir.',
      'potential-conflict': 'Aynı ayarı değiştiren başka bir aktif protokol var; ikisi çakışabilir.',
      'threshold-oscillation-risk': 'Eşik değerleri birbirine çok yakın; sık mod değişimi oluşabilir.',
      'long-delay': 'Geciktirme süresi görev döngüsünden uzun olabilir.',
    },
  },
  protocolManager: {
    title: 'PROTOKOLLER',
    intro: 'Kolonideki otomasyon protokolleri. Her kart protokolün ne yaptığını, hangi sistemleri etkilediğini ve en son ne zaman çalıştığını gösterir.',
    search: { label: 'Protokol ara', placeholder: 'Ad, tesis veya özet içinde ara', clear: 'Aramayı temizle' },
    filters: {
      label: 'Protokol filtreleri', lifecycle: 'DURUM', priority: 'ÖNCELİK', facility: 'TESİS',
      allFacilities: 'Tüm tesisler', allPriorities: 'Tüm öncelikler', clear: 'Filtreleri temizle',
    },
    results: {
      count: '{{shown}} / {{total}} protokol', empty: 'Bu arama ve filtrelerle eşleşen protokol yok.',
      emptyLibrary: 'Henüz protokol yok. Yeni bir protokol oluşturarak başlayabilirsin.',
    },
    create: { action: '+ Yeni Protokol', defaultName: 'Adsız Protokol' },
    card: {
      edit: 'Düzenle',
      summary: 'NE YAPAR', affected: 'ETKİLENEN SİSTEMLER', lastRun: 'SON ÇALIŞMA', priority: 'ÖNCELİK',
      status: 'DURUM', scale: '{{nodes}} düğüm · sürüm {{version}}', noFacility: 'Şu anda hiçbir tesise bağlı değil',
    },
    lifecycle: { active: 'Aktif', archived: 'Arşivlenmiş', disabled: 'Devre dışı', draft: 'Taslak', validated: 'Doğrulanmış' },
    priority: { critical: 'Kritik', high: 'Yüksek', low: 'Düşük', normal: 'Normal' },
    lastRun: {
      never: 'Henüz çalışmadı', at: '{{day}}. gün {{time}}', entry: '{{status}} · {{time}}',
      status: { applied: 'Uygulandı', blocked: 'Engellendi', delayed: 'Geciktirildi', failed: 'Başarısız', triggered: 'Tetiklendi' },
    },
    facility: {
      'battery-01': 'Batarya', habitat: 'Habitat', 'material-storage-01': 'Malzeme Deposu', 'mine-01': 'Maden',
      'oxygen-processor-01': 'Oksijen İşleyici', 'oxygen-reserve-01': 'Oksijen Rezerv Tankı', 'reactor-01': 'Reaktör',
    },
    measurement: { 'energy-level': '{{facility}} enerji seviyesi', 'facility-condition': '{{facility}} kondisyonu' },
    measurementGlobal: { 'energy-level': 'Koloni enerji seviyesi', 'facility-condition': 'Tesis kondisyonu' },
    value: {
      boolean: { off: 'Kapalı', on: 'Açık' },
      mode: { boost: 'Boost', eco: 'Eco', normal: 'Normal' },
      operatingState: { failed: 'Arızalı', interlocked: 'Güvenlik kilidinde', maintenance: 'Bakımda', offline: 'Devre dışı', online: 'Aktif', standby: 'Beklemede', starting: 'Başlatılıyor' },
      priority: { critical: 'Kritik', high: 'Yüksek', low: 'Düşük', normal: 'Normal' },
    },
    summary: {
      and: ' ve ',
      sentence: '{{body}}.',
      noTrigger: 'Bu protokolde başlangıç tetikleyicisi yok; kendiliğinden çalışamaz.',
      noAction: 'henüz hiçbir şey yapmıyor',
      unassignedFacility: 'hedefi belirlenmemiş tesis',
      unsetValue: 'belirlenmemiş değer',
      delayMinutes: '{{minutes}} dakika sonra',
      delayHours: '{{hours}} saat sonra',
      trigger: {
        above: '{{measurement}} {{threshold}} değerinin üstüne çıktığında',
        atLeast: '{{measurement}} {{threshold}} değerine veya üstüne çıktığında',
        atMost: '{{measurement}} {{threshold}} değerine veya altına indiğinde',
        below: '{{measurement}} {{threshold}} değerinin altına düştüğünde',
        equal: '{{measurement}} {{threshold}} değerine eşit olduğunda',
        notEqual: '{{measurement}} {{threshold}} değerinden farklı olduğunda',
      },
      condition: {
        above: '{{measurement}} {{value}} değerinin üstündeyse',
        atLeast: '{{measurement}} en az {{value}} ise',
        atMost: '{{measurement}} en fazla {{value}} ise',
        below: '{{measurement}} {{value}} değerinin altındaysa',
        equal: '{{measurement}} {{value}} ise',
        notEqual: '{{measurement}} {{value}} değilse',
        unknown: 'bağlı koşul sağlanıyorsa',
      },
    },
    action: {
      'set-condition': '{{facility}} tesisinin kondisyonunu {{value}} yapar',
      'set-energy-priority': '{{facility}} tesisinin enerji önceliğini {{value}} yapar',
      'set-maintenance-priority': '{{facility}} tesisinin bakım önceliğini {{value}} yapar',
      'set-mode': '{{facility}} tesisini {{value}} moduna alır',
      'set-operating-state': '{{facility}} tesisini {{value}} durumuna getirir',
      'set-work-priority': '{{facility}} tesisinin iş önceliğini {{value}} yapar',
      generic: '{{facility}} tesisinde {{action}} ayarını {{value}} yapar',
    },
  },
  protocolEditor: {
    back: '◂ Protokoller',
    canvasLabel: 'Protokol bağlantı tuvali',
    zoomIn: 'Yakınlaştır',
    zoomOut: 'Uzaklaştır',
    zoomLevel: '%{{percent}}',
    fitView: 'Ekrana sığdır',
    palette: { title: 'DÜĞÜM EKLE' },
    detail: {
      title: 'Düğüm Ayarları',
      empty: 'Ayarlarını görmek için bir düğüm seçin.',
      delete: 'Düğümü Sil',
    },
    actions: { apply: 'Uygula', check: 'Kontrol Et', saveDraft: 'Taslağı Kaydet' },
    unsaved: 'kaydedilmedi',
    check: {
      title: 'Doğrulama sonucu',
      clean: 'Protokol uygulanmaya hazır.',
      problems: '{{count}} sorun bulundu',
      warnings: '{{count}} uyarı',
      warningsHint: 'Yine de uygulanabilir.',
      more: '+{{count}} bulgu daha',
      dismiss: 'Sonucu kapat',
      focus: 'Düğüme git',
    },
    apply: {
      blockedUnchecked: 'Önce Kontrol Et ile doğrulayın.',
      blockedInvalid: 'Önce listelenen sorunları giderin.',
      done: 'Protokol uygulandı; simülasyonda çalışmaya başladı.',
      savedDraft: 'Taslak kaydedildi.',
    },
    finding: { error: 'Sorun', warning: 'Uyarı' },
    field: {
      allFacilities: 'Tüm tesisler',
      comparand: 'Sabit değer',
      compareConstant: 'Sabit bir değerle',
      compareMeasurement: 'Başka bir ölçümle',
      compareMode: 'Neyle karşılaştırılsın?',
      condition: 'Koşul',
      delayDuration: 'Bekleme süresi',
      delayHelp: 'İzin verilen aralık: {{minimum}}–{{maximum}} sim. dakika.',
      delaySuffix: 'sim. dakika',
      facility: 'Tesis',
      facilityHelp: 'Boş bırakılırsa koloni genelindeki ölçüm kullanılır.',
      measurement: 'Ölçüm',
      setting: 'Yapılacak ayar',
      targetFacility: 'Hedef tesis',
      threshold: 'Eşik değeri',
      unset: 'Seçilmedi',
      value: 'Ayarlanacak değer',
    },
    operatorChoice: {
      above: 'değerin üstüne çıkarsa',
      atLeast: 'değere çıkar veya üstüne geçerse',
      atMost: 'değere iner veya altına düşerse',
      below: 'değerin altına düşerse',
      equal: 'değere eşit olursa',
      notEqual: 'değerden farklı olursa',
    },
    node: { action: 'Eylem', and: 'VE', compare: 'Karşılaştır', delay: 'Geciktir', sensor: 'Sensör', trigger: 'Tetikleyici' },
    nodeDescription: {
      action: 'Hedef tesiste bir ayarı değiştirir.',
      and: 'Her iki koşul da sağlandığında akış devam eder.',
      compare: 'İki değeri karşılaştırır ve sonucuna göre yolu ayırır.',
      delay: 'Belirtilen süre kadar bekletir, sonra devam eder.',
      sensor: 'Bu düğüm yalnız bir değeri okur; protokolü kendi başına başlatmaz.',
      trigger: 'Protokolü başlatan koşul.',
    },
    port: {
      a: '1. koşul', b: '2. koşul', in: 'Akış', left: 'Değer', out: 'Akış',
      result: 'Sonuç', right: 'İkinci değer', value: 'Ölçüm', whenFalse: 'Hayır', whenTrue: 'Evet',
    },
    edge: { no: 'Hayır', yes: 'Evet' },
    card: {
      action: '{{setting}} · {{value}}',
      compareTwoValues: 'İki ölçümü karşılaştırır',
      condition: {
        above: '{{value}} değerinin üstüne çıkarsa',
        atLeast: '{{value}} değerine çıkar veya üstüne geçerse',
        atMost: '{{value}} değerine iner veya altına düşerse',
        below: '{{value}} değerinin altına düşerse',
        equal: '{{value}} değerine eşit olursa',
        notEqual: '{{value}} değerinden farklı olursa',
      },
      delay: '{{minutes}} sim. dakika bekler',
      unsetMeasurement: 'Ölçüm seçilmedi',
      unsetSetting: 'Ayar seçilmedi',
    },
    setting: {
      'set-condition': 'Kondisyon', 'set-energy-priority': 'Enerji önceliği', 'set-maintenance-priority': 'Bakım önceliği',
      'set-mode': 'Çalışma modu', 'set-operating-state': 'Çalışma durumu', 'set-work-priority': 'İş önceliği',
    },
    connection: {
      cycle: 'Bu bağlantı akışı kendi üzerine döndürür; protokol döngüye giremez.',
      direction: 'Bağlantı bir düğümün çıkışından başka bir düğümün girişine kurulur.',
      duplicate: 'Bu bağlantı zaten kurulmuş.',
      'input-occupied': 'Bu giriş noktası zaten bağlı; önce mevcut bağlantıyı kaldırın.',
      'self-connection': 'Bir düğüm kendisine bağlanamaz.',
      'type-mismatch': 'Bu iki bağlantı noktası farklı türde bilgi taşıyor; birbirine bağlanamaz.',
      'unknown-port': 'Bu bağlantı noktası artık yok; düğümü yeniden seçin.',
    },
  },
  simulationDiagnostic: {
    actions: {
      advance60: '+60 Sim. Dakika İlerle',
      maintenancePriority: 'Bakım Önceliği: {{priority}}',
      mine: { boost: 'Maden: Boost', eco: 'Maden: Eco', normal: 'Maden: Normal', offline: 'Madeni Devre Dışı Bırak', online: 'Madeni Etkinleştir' },
      mineCondition: 'Maden Kondisyonu: {{condition}}',
      pause: 'Duraklat',
    },
    command: { none: 'SON KOMUT: Yok', result: 'SON KOMUT: {{status}}{{reason}}' },
    conditionFixtures: 'Maden kondisyon denemeleri',
    empty: { maintenance: 'BAKIM: Bakım ihtiyacı yok', travel: 'YOLCULUK: Kimse yolda değil' },
    facility: {
      condition: 'KONDİSYON {{condition}} · {{band}} · AŞINMA {{wear}}/sa.',
      workforce: 'İŞ GÜCÜ {{assigned}}/{{nominal}} · TESİSTE {{onSite}}',
    },
    help: {
      active: 'Şu anda çalışabilecek kolonici sayısı',
      assigned: 'Bir tesis veya bakım görevine ayrılmış kolonici',
      available: 'Aktif fakat şu anda görevi olmayan kolonici',
      condition: 'Kondisyon tesisin 0–100 teknik sağlığıdır; aşınma çalıştıkça bu değeri düşüren orandır.',
      resting: 'Habitat içinde dinlenen kolonici',
      traveling: 'Bir göreve veya Habitat’a fiziksel olarak hareket eden kolonici',
    },
    labels: {
      active: 'AKTİF İŞ GÜCÜ', assigned: 'GÖREVE ATANMIŞ', available: 'MÜSAİT', day: 'GÜN', dayPhase: 'ZAMAN DİLİMİ', elapsed: 'GEÇEN SİM. DAKİKASI',
      energyPriority: 'ENERJİ ÖNCELİĞİ', localTime: 'YEREL SAAT (SİM.)', mineState: 'MADEN DURUMU', mode: 'MOD', population: 'NÜFUS',
      resting: 'DİNLENİYOR', simStep: 'SİMÜLASYON ADIMI', speed: 'HIZ', traveling: 'YOLDA', worldPresentation: 'DÜNYA GÖRSEL DURUMU', x1Rate: '×1 ORANI',
    },
    maintenance: {
      detail: 'MALZEME {{material}}{{consumed}} · KALAN {{remaining}} sim. dk.{{reason}}',
      workforce: 'ÖNCELİK {{priority}} · İŞÇİ {{assigned}}/{{required}}',
    },
    maintenancePriority: 'Maden bakım önceliği',
    mineCommands: 'Maden simülasyon komutları',
    minutes: '{{count}} dk.',
    phaseBadge: 'DEV · FAZ 3',
    resourceRate: '+{{production}} −{{consumption}} = {{net}}/sa.',
    speedControls: 'Simülasyon hız kontrolleri',
    title: 'SİMÜLASYON DURUMU',
    travel: {
      detail: '{{purpose}} · İLERLEME %{{progress}} · KALAN {{remaining}} sim. dk.',
      route: '{{from}} → {{to}}',
    },
    values: {
      commandStatus: { applied: 'Uygulandı', blocked: 'Engellendi', delayed: 'Geciktirildi', failed: 'Başarısız' },
      condition: { critical: 'Kritik', failed: 'Arızalı', healthy: 'Sağlıklı', worn: 'Yıpranmış' },
      consumed: ' · TÜKETİLDİ',
      dayPhase: { day: 'Gündüz', night: 'Gece' },
      facilityState: { failed: 'Arızalı', interlocked: 'Güvenlik kilidinde', maintenance: 'Bakımda', offline: 'Devre dışı', online: 'Aktif', standby: 'Beklemede', starting: 'Başlatılıyor' },
      location: { 'battery-01': 'Batarya', habitat: 'Habitat', 'mine-01': 'Maden', 'oxygen-processor-01': 'Oksijen İşleyici', 'reactor-01': 'Reaktör' },
      maintenanceStatus: { completed: 'Bakım tamamlandı', 'in-progress': 'Bakım yapılıyor', requested: 'Bakım istendi', traveling: 'Bakım ekibi yolda', 'waiting-resources': 'Kaynak bekliyor', 'waiting-workforce': 'İş gücü bekliyor' },
      mode: { boost: 'Boost (Yüksek Güç)', eco: 'Eco (Tasarruf)', normal: 'Normal' },
      none: 'Yok',
      paused: 'DURAKLATILDI',
      priority: { critical: 'Kritik', high: 'Yüksek', low: 'Düşük', normal: 'Normal' },
      resource: { energy: 'ENERJİ', material: 'MALZEME', oxygen: 'OKSİJEN' },
      running: 'ÇALIŞIYOR',
      travelPurpose: { 'return-to-habitat': 'Habitat’a dönüyor', 'to-assignment': 'Göreve gidiyor' },
    },
    x1Rate: '1 sim. dk. ≈ {{value}} gerçek sn.',
  },
} as const;
